### ISSUE TITLE
Faulty shape of SphericalExpansion

### ISSUE THREAD

**Issue by sirmarcel** [Luthaf/rascaline#294] opened 2024-04-08 11:24 UTC
Hello, I think I've found a bug in `rascaline` while trying to write a test for `torch_spex`: For a test system with 3 atoms and 2 species, the output of `SphericalExpansion` has the wrong shape (in some cases):

```
from ase import Atoms
import numpy as np

import rascaline

atoms = Atoms(
    positions=np.array([[0, 0, 0], [1, 0, 0], [0, 0, 1]]),
    numbers=[1, 1, 2],
    cell=np.eye(3) * 10,
    pbc=True,
)

cutoff = 1.1
max_angular = 6
max_radial = 8


spliner = rascaline.utils.SoapSpliner(
    cutoff=cutoff,
    max_radial=max_radial,
    max_angular=max_angular,
    basis=rascaline.utils.SphericalBesselBasis(
        cutoff=cutoff, max_radial=max_radial, max_angular=max_angular
    ),
    density=rascaline.utils.DeltaDensity(),
    accuracy=1e-8,
)

splined_basis = spliner.compute()

calculator = rascaline.SphericalExpansion(
    cutoff=cutoff,
    max_radial=max_radial,
    max_angular=max_angular,
    center_atom_weight=0.0,
    radial_basis=splined_basis,
    atomic_gaussian_width=-1.0,  # will not be used due to the delta density above
    cutoff_function={"ShiftedCosine": {"width": 0.5}},
)

d1 = calculator.compute([atoms])

assert (
    d1[
        {
            "spherical_harmonics_l": 0,
            "species_center": 1,
            "species_neighbor": 1,
        }
    ].values.shape[0]
    == 2
)  # -> this passes

assert (
    d1[
        {
            "spherical_harmonics_l": 0,
            "species_center": 1,
            "species_neighbor": 2,
        }
    ].values.shape[0]
    == 2
)  # -> this fails
```

Since there are two atoms of species `1`, the shape should, as far as I understand, always be `[2, ...]`, not `[1, ...]`. Note also that this only occurs for different center and neighbor species.

System info:
- `rascaline==0.1.0.dev518`
- `python==3.12.2`
- macOS 14.3.1 on M3 Max

**Comment by Luthaf** [comment] 2024-04-08 16:23
Right, only the actual neighbors are included in the outptut by default. The idea was that people can use `selected_samples` if they want to make sure all samples are always included (even if they would be zero everywhere). See https://luthaf.fr/rascaline/latest/how-to/sample-selection.html for a quick tutorial on this.

**Comment by Luthaf** [comment] 2024-04-09 14:03
Closing, this is working as intended 😃

**Closed by Luthaf** 2024-04-09 14:03 UTC
