### ISSUE TITLE
Friction compiling tests on Ubuntu

### ISSUE THREAD

**Issue by agoscinski** [Luthaf/rascaline#4] opened 2021-02-19 20:13 UTC
Not sure if this can be made simpler for Ubuntu users by switching to lower versions, just wanted to share my installation experience.

So there is no GSL-3.0 version for Ubuntu
https://github.com/Luthaf/rascaline/blob/ca9256756c92e0e150fdbe7477be0fe1852aaf1e/rascaline/Cargo.toml#L33
since the newest stable version is 2.6 according to https://www.gnu.org/software/gsl/
For a temporary fix of below error I switched it to 2.0.1
```
error: aborting due to 2070 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `GSL`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rgsl /home/alexgo/.cargo/registry/src/github.com-1ecc6299db9ec823/GSL-3.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type dylib --crate-type rlib --emit=dep-info,link -C prefer-dynamic -Cembed-bitcode=no -C debuginfo=2 -C metadata=f1559776a8bfee96 -C extra-filename=-f1559776a8bfee96 --out-dir /home/alexgo/lib/rascaline/target/debug/deps -L dependency=/home/alexgo/lib/rascaline/target/debug/deps --extern gsl_sys=/home/alexgo/lib/rascaline/target/debug/deps/libgsl_sys-8f5b7f66dff3843b.so --extern gsl_sys=/home/alexgo/lib/rascaline/target/debug/deps/libgsl_sys-8f5b7f66dff3843b.rlib --extern paste=/home/alexgo/lib/rascaline/target/debug/deps/libpaste-07ae39ea28b6635f.so --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
```

I had to update my cmake version to a version above the currently one offered by standard apt repositories
```CMake 3.11 or higher is required.  You are running version 3.10.2```
(Helpful installation instruction https://askubuntu.com/a/865294)

Same for rust version
```
  your Rust installation is too old (you have version cargo 1.46.0

  ), at least 1.48.0 is required
```
Can be simply installed https://doc.rust-lang.org/cargo/getting-started/installation.html
but cmake apparently cannot find cargo
```
-- CARGO_STATUS No such file or directory CARGO_VERSION      CMAKE_SYSTEM_PROGRAM_PATH 
CMake Error at ../../../CMakeLists.txt:47 (message):
  could not run cargo, please make sure the Rust compiler is installed (see
  https://www.rust-lang.org/tools/install)
```
I linked a the binary in the home directory to /usr/local/bin but still nothing.
I am not sure how cmake finds programs usually, there are a lot of steps which can be checked https://cmake.org/cmake/help/latest/command/find_program.html
Here I gave up and just hide the `rascaline-c-api/tests/c-api.rs` file and it works :)

**Comment by Luthaf** [comment] 2021-02-19 22:49
I'm sorry this is still very much in a prototype state, and not very easy to install =(. Thanks a lot for kicking the tires and helping to make this a smoother experience! Just to be clear, this is on ubuntu 18.04?

> So there is no GSL-3.0 version for Ubuntu

This is the version of the Rust GSL bindings (https://docs.rs/GSL/), not the GSL library itself. The only thing needed (as indicated in the README) is to run `apt install libgsl0-dev` to install the GSL library.

I think we should replace GSL by regression tests anyway, this was mostly an easy dependency to check that the math code was right while prototyping =)

> I had to update my cmake version to a version above the currently one offered by standard apt repositories

This is a bit unfortunate, since there is no way to attach a header directory to an imported target in cmake < 3.11. Maybe we could not run the C API tests if the cmake version the user have is too old? I'll look into possible alternatives.

> Same for rust version

You have 1.46.0, is this the version in the apt repository? I think I had to increase the minimal rust version because of GSL, so if we get rid of it this should be better.

>  but cmake apparently cannot find cargo

Did you restart your shell after installing cargo? What is in your PATH?

**Comment by agoscinski** [comment] 2021-02-20 10:05
> I'm sorry this is still very much in a prototype state, and not very easy to install =(. Thanks a lot for kicking the tires and helping to make this a smoother experience! Just to be clear, this is on ubuntu 18.04?

yes it is ubuntu 18.04
<br>
<br>
> This is the version of the Rust GSL bindings (https://docs.rs/GSL/), not the GSL library itself. The only thing needed (as indicated in the README) is to run apt install libgsl0-dev to install the GSL library

I have done this. The default GSL apt version is 2.4, but there is also no 3.0 to update to. In the example they also use the 3.0 version https://crates.io/crates/GSL I guess it is just wrong, since the most recent version is 2.6
<br>
<br>

> You have 1.46.0, is this the version in the apt repository? I think I had to increase the minimal rust version because of GSL, so if we get rid of it this should be better.

Yes 1.46.0 was from apt repository
<br>
<br>

> Did you restart your shell after installing cargo? What is in your PATH?

Yes also removed target folder and recompiled, my bash could find cargo. In my PATH is `/usr/local/bin` which has a link to cargo, so `/usr/local/bin/cargo` works. This I can investigate more some time, when I fell like dealing with cmake :-)

**Comment by Luthaf** [comment] 2021-02-20 13:08
> I have done this. The default GSL apt version is 2.4, but there is also no 3.0 to update to. In the example they also use the 3.0 version https://crates.io/crates/GSL I guess it is just wrong, since the most recent version is 2.6

https://crates.io/crates/GSL is the nice Rust API built on top of the GSL library, and uses a separate version number from the GSL library itself. The raw library is available as https://crates.io/crates/GSL-sys, which has the same version number (`2.0.1`) as the C library.

**Comment by Luthaf** [comment] 2021-02-24 11:28
All these issues should be fixed now! Can you try uninstalling the rustup version of the compiler and GSL; and try again with the version of rust provided by Ubuntu?

**Closed** 2021-02-24 11:27 UTC
